<a href="https://colab.research.google.com/github/AnjaliSharma2002/Assignments/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Theoretical Questions:

In [2]:
# Q1.

# NumPy (Numerical Python) is a foundational library in Python for numerical computing. It provides efficient and flexible data structures, primarily the ndarray (N-dimensional array), along with a wide range of mathematical functions optimized for performance.

# Purpose:
# NumPy provides efficient numerical operations, handling large datasets with optimized performance, making it essential for scientific computing and data analysis.

# Advantages:
# Faster Computation – Uses optimized C-based operations.
# Memory Efficient – Stores homogeneous data in contiguous memory.
# Broadcasting – Allows operations on arrays of different shapes.
# Rich Math Functions – Supports linear algebra, FFT, statistics, etc.
# Seamless Integration – Works well with Pandas, SciPy, TensorFlow, etc.

# This enhances Python’s capabilities for high-speed numerical computing and large-scale data processing.

In [3]:
# Q2.

# Both np.mean() and np.average() are used to compute the mean of an array, but they differ in functionality.

# np.mean() calculates the simple arithmetic mean, where all elements contribute equally. It does not support weights, making it ideal for cases where each value is equally significant.

# On the other hand, np.average() allows for weighting, meaning you can assign different importance to each element. If no weights are provided, it behaves like np.mean(). However, when weights are included, it computes a weighted mean, where elements with higher weights contribute more to the final result.

# Use np.mean() when all values should be treated equally, such as computing the average temperature over a week.

# Use np.average() when certain values should have more influence, such as calculating a weighted exam score where different assignments have different weightages.

In [4]:
# Q3.

# NumPy provides multiple ways to reverse arrays, depending on their dimensions and the required axis of reversal.

# For 1D array

import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])

rev_1d = arr_1d[::-1]

rev_1d_flip = np.flip(arr_1d)

print(rev_1d)
print(rev_1d_flip)


[5 4 3 2 1]
[5 4 3 2 1]


In [5]:
# For 2D array

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

rev_rows = arr_2d[::-1, :]

rev_cols = arr_2d[:, ::-1]

rev_both = arr_2d[::-1, ::-1]

print(rev_rows)

print(rev_cols)

print(rev_both)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [7]:
# Q4.


# To check the data type of a NumPy array using the .dtype attribute:

import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("Data Type:", arr.dtype)

# Data types (dtype) in NumPy are crucial for efficient memory management, computational performance, and numerical accuracy. Choosing the right data type ensures optimal use of system resources and prevents errors in numerical operations.

Data Type: int32


In [8]:
# Q5.

# In NumPy, an ndarray (N-dimensional array) is a powerful data structure used for efficient numerical computing. It is a homogeneous, multi-dimensional container for storing and manipulating numerical data.

# Key Features of ndarray
# Homogeneous Data – All elements in an ndarray must be of the same data type (int, float, etc.).
# Efficient Memory Management – Stores elements in contiguous memory blocks, reducing overhead.
# Supports Vectorized Operations – Performs element-wise operations without explicit loops, improving performance.
# Multidimensional Support – Can have multiple dimensions (1D, 2D, 3D, etc.).
# Broadcasting – Enables operations on arrays of different shapes without manual resizing.
# Fast Mathematical Operations – Optimized with C and Fortran, making computations significantly faster than Python lists.


# Difference Between NumPy ndarray and Python Lists

# 1. Data Type Consistency

# ndarray: Homogeneous (same data type).
# List: Heterogeneous (mixed types allowed).

# 2. Memory Efficiency

# ndarray: Uses less memory (contiguous storage).
# List: Requires more memory (stores references).

# 3. Performance

# ndarray: Faster due to vectorized operations.
# List: Slower, requires loops for calculations.

# 4. Multi-dimensional Support

# ndarray: Supports multi-dimensional arrays easily.
# List: Needs nested lists, making indexing complex.

# 5. Mathematical Operations

# ndarray: Built-in math functions (np.mean(), np.sum()).
# List: Requires manual implementation (sum()/len()).

In [9]:
# Q6.

# Performance Benefits of NumPy Arrays Over Python Lists

# Memory Efficiency

# NumPy stores data in contiguous memory blocks, using less memory.
# Python lists store references, consuming more space.

# Faster Computation (Vectorization)

# NumPy performs vectorized operations using optimized C code.
# Python lists require explicit loops, slowing down calculations.

# Efficient Broadcasting

# NumPy allows operations on arrays of different shapes without extra loops.
# Python lists require manual iteration and resizing.

# Optimized Mathematical Functions

# NumPy has built-in functions (np.mean(), np.sum()) that are faster than Python loops.

In [11]:
# Q7.

# Both vstack() and hstack() are used to stack (combine) arrays, but they differ in how they align the arrays:

# np.vstack() (Vertical Stack) → Stacks arrays row-wise (along axis 0).
# np.hstack() (Horizontal Stack) → Stacks arrays column-wise (along axis 1).

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_v = np.vstack((arr1, arr2))

print(result_v)


[[1 2 3]
 [4 5 6]]


In [12]:
result_h = np.hstack((arr1, arr2))

print(result_h)


[1 2 3 4 5 6]


In [14]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

print(np.vstack((arr3, arr4)))
print(np.hstack((arr3, arr4)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# Q8.

# Both fliplr() and flipud() are used to flip (reverse) arrays, but they operate on different axes:

# fliplr() (Flip Left-Right)

# Reverses columns (left-to-right flip).
# Works on 2D arrays and higher (does nothing for 1D arrays).
# flipud() (Flip Up-Down)

# Reverses rows (top-to-bottom flip).
# Works on 2D arrays and higher.

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(np.fliplr(arr))
print(np.flipud(arr))


# Effect on Different Dimensions
# 1D array: fliplr() does nothing, but flipud() works like [::-1].
# 2D array: fliplr() flips columns, flipud() flips rows.
# 3D+ array: fliplr() and flipud() affect the last two dimensions.

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [17]:
# Q9.

# The np.array_split() method is used to split an array into multiple sub-arrays. It is similar to np.split(), but with a key difference:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.array_split(arr, 3)
print(split_arr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
split_arr = np.array_split(arr2D, 2, axis=1)  # Splitting columns

print(split_arr)


[array([[1, 2],
       [4, 5]]), array([[3],
       [6]])]


In [19]:
# Q10.

# Vectorization and broadcasting are two key features of NumPy that make array operations efficient, fast, and memory-friendly by eliminating explicit loops.

# Vectorization refers to performing operations on entire arrays at once, rather than looping through elements one by one. NumPy achieves this by leveraging highly optimized C and Fortran libraries.

import numpy as np

arr = np.array([1, 2, 3, 4])

# Without vectorization (using loops)
result = [x * 2 for x in arr]
print(result)

# With vectorization
result_vec = arr * 2
print(result_vec)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]
[2 4 6 8]


In [20]:
# Broadcasting allows NumPy to perform operations on arrays of different shapes without explicit looping or reshaping. It automatically expands smaller arrays to match the dimensions of larger arrays.

arr = np.array([1, 2, 3])
print(arr + 5)

[6 7 8]


In [21]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

print(arr1 + arr2)


[[2 4 6]
 [5 7 9]]


In [22]:
# Practical Questions:

In [24]:
# Q1.

import random

arr = np.random.randint(1,100,(3,3))
arr

array([[51, 14, 89],
       [73, 42, 57],
       [61,  8, 78]])

In [25]:
arr.T

array([[51, 73, 61],
       [14, 42,  8],
       [89, 57, 78]])

In [27]:
# Q2.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr_2x5 = arr.reshape(2, 5)
print("2x5 Array:\n", arr_2x5)

arr_5x2 = arr.reshape(5, 2)
print("5x2 Array:\n", arr_5x2)


2x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5x2 Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [28]:
# Q3.

import numpy as np

arr = np.random.rand(4, 4)
print("Original 4x4 Array:\n", arr)

arr_with_border = np.zeros((6, 6))

arr_with_border[1:-1, 1:-1] = arr
print("\n6x6 Array with Zero Border:\n", arr_with_border)


Original 4x4 Array:
 [[0.87300384 0.62162091 0.11359302 0.02540673]
 [0.52946014 0.07470063 0.70241622 0.00305072]
 [0.78354553 0.92211232 0.46973563 0.96707137]
 [0.51486448 0.84812774 0.25412049 0.34870831]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.87300384 0.62162091 0.11359302 0.02540673 0.        ]
 [0.         0.52946014 0.07470063 0.70241622 0.00305072 0.        ]
 [0.         0.78354553 0.92211232 0.46973563 0.96707137 0.        ]
 [0.         0.51486448 0.84812774 0.25412049 0.34870831 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [29]:
# Q4.

import numpy as np

arr = np.arange(10, 65, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [30]:
# Q5.

import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)

print("Original Array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title Case:", titlecase_arr)
print("Capitalize:", capitalize_arr)

Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


In [31]:
# Q6.

import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

spaced_arr = np.char.join(' ', arr)

print(spaced_arr)


['p y t h o n' 'n u m p y' 'p a n d a s']


In [33]:
# Q7.

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)

Addition:
 [[ 8 10 12]
 [14 16 18]]

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [34]:
# Q8.

import numpy as np

identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [35]:
# Q9.

import numpy as np

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

arr = np.random.randint(0, 1000, 100)

prime_numbers = arr[np.vectorize(is_prime)(arr)]

print("Original Array:\n", arr)
print("\nPrime Numbers:\n", prime_numbers)


Original Array:
 [ 16 174 231  53 370 642 555 102 322 337  17 937 173 472 431 458 794 942
 734 165 266 737 627 990  55 137 598 810 134 907 756 165 455 899 797 810
 846  92  76 239 904  20 428 845  51 261 389 672 649 477 275 915 510  57
 261 145 372 497 524  99 175 970 875 921 723 332 335 388  11 406  16 307
 154 393 486 339 788 298 684  96 448 228 783 162 495 832 169 408 292 419
  45 428  29 420 732 274 633 857 687 931]

Prime Numbers:
 [ 53 337  17 937 173 431 137 907 797 239 389  11 307 419  29 857]


In [36]:
# Q10.

import numpy as np

daily_temps = np.random.uniform(15, 35, 30)
print("Daily Temperatures:\n", daily_temps)

weeks = daily_temps[:28].reshape(4, 7)
extra_days = daily_temps[28:]

weekly_averages = np.mean(weeks, axis=1)

if extra_days.size > 0:
    extra_week_avg = np.mean(extra_days)
    weekly_averages = np.append(weekly_averages, extra_week_avg)

print("\nWeekly Averages:\n", weekly_averages)


Daily Temperatures:
 [28.1679773  32.95492159 30.54861913 21.09082609 23.7867338  17.06989763
 31.49315701 22.79995592 30.46097818 32.71088065 26.24113119 31.11770984
 29.18663826 34.49562755 29.14496608 24.75411879 18.50069127 30.25427509
 30.07783484 34.53816134 32.5844525  33.74359183 19.13690481 17.15532745
 29.1911325  32.79145756 30.77550814 20.26859789 16.34322313 30.23513418]

Weekly Averages:
 [26.44459037 29.57327451 28.55064284 26.1517886  23.28917866]
